### PR TITLE
Follow golint initialisms rules

### PR DESCRIPTION
**Pull request by ThomasBS**
- Edited code to follow the [initialism ruleset](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

`golint` is still complaining about exported structs not being commented, but I thought this would be a kick in the right direction.

### CODE REVIEW

**Comment by ofmadsen** [comment]
Great idea! 

All the tags where JSON key names now match the struct fields should be removed before I can accept the pull request. Just to remove unnecessary clutter. Like so:

``` go
// Redundant
FormattedID string `json:"FormattedID"`

// Nice!
FormattedID string
```

:horse: Thanks!

**Comment by ThomasBS** [comment]
Your wish is my command :horse:

**Comment by ofmadsen** [comment]
Super!

However, given a closer look, shouldn't the conversion of `Uri` to `URI` result in an added `json:"Uri"` JSON key name?

:horse: Thanks!

**Comment by ThomasBS** [comment]
No, that should not be necessary.

Taken from go docs:

> How does Unmarshal identify the fields in which to store the decoded data? For a given JSON key "Foo", Unmarshal will look through the destination struct's fields to find (in order of preference):
> - An exported field with a tag of "Foo" (see the Go spec for more on struct tags),
> - An exported field named "Foo", or
> - An exported field named "FOO" or "FoO" or some other case-insensitive match of "Foo".

I made a quick [playgound fiddle](http://play.golang.org/p/dPmnXU9beK) to showcase!

**Comment by ofmadsen** [comment]
Awesome - thanks for clarifying that!

**Pull request merged**
